# https://github.com/actions/go-dependency-submission
name: dependency-submission
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run snapshot action
        uses: actions/go-dependency-submission@v2
        with:
            go-mod-path: go.mod
            go-build-target: cmd/omitlint/main.go
